// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_hello
List rcpp_hello();
RcppExport SEXP _ksRcpp_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}

RcppExport void C_interp1d(void *, void *, void *, void *, void *, void *, void *);
RcppExport void C_interp2d(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void C_interp3d(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void C_massdist1d(void *, void *, void *, void *, void *, void *, void *);
RcppExport void C_massdist2d(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void C_massdist3d(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);
RcppExport void C_massdist4d(void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *, void *);

static const R_CallMethodDef CallEntries[] = {
    {"_ksRcpp_rcpp_hello", (DL_FUNC) &_ksRcpp_rcpp_hello, 0},
    {"C_interp1d",   (DL_FUNC) &C_interp1d,    7},
    {"C_interp2d",   (DL_FUNC) &C_interp2d,   11},
    {"C_interp3d",   (DL_FUNC) &C_interp3d,   15},
    {"C_massdist1d", (DL_FUNC) &C_massdist1d,  7},
    {"C_massdist2d", (DL_FUNC) &C_massdist2d, 11},
    {"C_massdist3d", (DL_FUNC) &C_massdist3d, 15},
    {"C_massdist4d", (DL_FUNC) &C_massdist4d, 19},
    {NULL, NULL, 0}
};

RcppExport void R_init_ksRcpp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
